language: python
python:
 - "3.6"

branches:
  only:
    - master

install:
 - pip install mkdocs
 - pip install mkdocs-material

script: 
 - mkdocs build --clean
 - mkdocs build

deploy:
  provider: surge
  project: ./site
  domain: juandi.surge.sh
  skip_cleanup: true
