language: python
python:
 - "3.6"

branches:
  only:
    - master

install:
 - pip install mkdocs
 - pip install mkdocs-material

script: 
 - mkdocs build --clean
 - mkdocs build -d web/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: web/
  fqdn: www.juandinoguera.tk
  on:
    branch: master
